import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#B09AFF',   
    padding: 20,
  },
  title: {
    fontSize: 40,
    fontWeight: '800',
    color: '#4A148C',           
    alignSelf: 'center',
    marginBottom: 10,
    marginTop: 20,
    fontFamily: 'ConcertOne_400Regular',
  },
  resultBox: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 16,
    alignSelf: 'center',
    width: '60%',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    borderColor: "rgb(74, 20, 140)",
    borderWidth: 3,
  },
  resultText: {
    fontSize: 22,
    color: '#4A148C',
    textAlign: 'left',  
    fontFamily: 'ConcertOne_400Regular',
  },
  NoresultText: {
    fontSize: 25,
    color: '#4A148C',
    textAlign: 'center',  
    fontFamily: 'ConcertOne_400Regular',
  },
  topListTitle: {
    fontSize: 30,
    color: '#4A148C',
    alignSelf: 'center',
    textAlign: 'center',
    marginBottom: 12,
    fontFamily: 'ConcertOne_400Regular',
  },
  TopresultBox: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 16,
    alignSelf: 'center',
    width: '85%',

    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    borderColor: "rgb(74, 20, 140)",
    borderWidth: 3,
    flex: 1,
  },
  scrollView: {
    width: '100%',
  },
  resultItem: {
    backgroundColor: '#B09AFF',
    padding: 10,
    borderRadius: 12,
    marginBottom: 5,
    alignSelf: 'center',
    width: '100%',
    borderColor: "rgb(74, 20, 140)",
    borderWidth: 3,
    borderRadius: 10,
  },
  rank: {
    fontSize: 30,
    fontWeight: '700',
    color: '#4A148C',
    marginBottom: 2,
    fontFamily: 'ConcertOne_400Regular',
  },
  resultItemText: {
    fontSize: 18,
    color: '#4A148C',
    marginVertical: 2,
    fontFamily: 'ConcertOne_400Regular',
  },
  ButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 10,
    marginBottom: 20,
  },
  homeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor:'#4A148C',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginHorizontal: 5,
  },
  homeButtonText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'ConcertOne_400Regular',
  },
  PlayAgainButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor:'#4A148C',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginHorizontal: 5,
  },
  PlayAgainButtonText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'ConcertOne_400Regular',
  },
});
