import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgb(153, 255, 204)", 
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  title: {
    fontSize: 40,
    fontWeight: "bold",
    color:  "rgb(4, 201, 103)", 
    marginBottom: 10,
    marginTop: 60,
    fontFamily: "Bungee_400Regular",
  },  
  title2: {
    fontSize: 30,
    fontWeight: "bold",
    color:  "rgb(4, 201, 103)", 
    marginBottom: 5,
    marginTop: 20,
    fontFamily: "Bungee_400Regular",
  },
  resultBox: {
    backgroundColor: "rgb(119, 250, 185)", 
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    width: "80%",
    alignItems: "center",
    borderColor: "rgb(0, 105, 53)",
    borderWidth: 3,
  },
  infoText: {
    fontSize: 20,
    color: "rgb(0, 105, 53)", 
    marginBottom: 5,
    fontFamily: "Bungee_400Regular",
    alignSelf: "flex-start",
  },
  scrollView: {
    width: "90%",
  },
  scoreItem: {
    backgroundColor: "rgb(119, 250, 185)", 
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderColor: "rgb(0, 105, 53)",
    borderWidth: 2,
  },
  scoreText: {
    fontSize: 18,
    color: "rgb(0, 105, 53)", 
    marginBottom: 2,
    fontFamily: "Bungee_400Regular",
  },
  noScores: {
    fontSize: 20,
    color: "rgb(0, 105, 53)", 
    textAlign: "center",
    marginTop: 10,
    fontFamily: "Bungee_400Regular",
  },
  difficultySection: {
    marginBottom: 15,
    backgroundColor: "rgb(76, 252, 164)", 
    padding: 10,
    borderRadius: 8,
    borderColor: "rgb(0, 105, 53)",
    borderWidth: 3,
  },
  difficultyTitle: {
    fontSize: 25,
    fontWeight: "bold",
    color:"rgb(0, 105, 53)", 
    marginBottom: 5,
    fontFamily: "Bungee_400Regular",
  },
  picker: {
    width: "80%",
    height: 50,
    backgroundColor: "white",
    color: "#333",
    marginBottom: 15,
    borderRadius: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
  },
  filterButton: {
    padding: 10,
    marginHorizontal: 5,
    backgroundColor: "rgb(76, 252, 164)",
    borderRadius: 5,
  },
  selectedButton: {
    backgroundColor: "rgb(71, 224, 148)",
  },
  buttonText: {
    color: "rgb(0, 105, 53)", 
    fontWeight: "bold",
    fontFamily: "Bungee_400Regular",
    fontSize: 15,
  },
  rank: {
    fontSize: 30,
    fontWeight: "bold",
    color: "rgb(0, 105, 53)",                                        
    marginBottom: 5,
    fontFamily: "Bungee_400Regular",
  },
  resultButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginVertical: 5,
  },
  Button: {
  backgroundColor: "rgb(76, 252, 164)", 
  padding: 10,
  marginHorizontal: 10,
  borderRadius: 5,
  flexDirection: 'row',
  alignItems: 'center', 
  },
  ButtonText: {
    color: "rgb(0, 105, 53)", 
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: "Bungee_400Regular",
  }
});

export default styles;