import { Dimensions, StyleSheet } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const containerMarginHorizontal = 15; 
const availableWidth = windowWidth - containerMarginHorizontal * 2;
const buttonMargin = 6;
const buttonWidth = (availableWidth - buttonMargin * 3) / 2;

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "lightblue",
    paddingBottom: 40,
  },
  title: {
    fontSize: 35,
    fontFamily: 'PressStart2P_400Regular',
    fontWeight: "bold",
    marginTop: 80,
    marginBottom: 20,
    color: "#222",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    width: "80%",
    height: 42,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 10,
    backgroundColor: "white",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: "90%",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "rgb(58, 226, 255)",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginHorizontal: 5,
    elevation: 3,
    marginRight: 20,
    marginLeft: 20,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  gameSection: {
    width: "95%",
    backgroundColor: "rgba(186, 245, 255, 0.73)",
    borderRadius: 18,
    padding: 10,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
    marginTop: 20,
    textAlign: "center",
  },
  fullScreen: {
    flex: 1,
    backgroundColor: 'lightblue',
  },
  scrollContainer: {
    flex: 1,
  },

  gameButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between', 
    paddingHorizontal: containerMarginHorizontal, 
  },
  backgroundImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '105%',
    height: '105%',
  },
  game2048Button: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center', 
  },
  game2048ButtonText: {
    color: "white",
    fontSize: 35,
    fontWeight: "600",
    textAlign: "center",
  },
  ShooterButton: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ShooterButtonText: {
    fontSize: 45,
    color: '#6C5DD3', 
    textAlign: "center",
    fontWeight: "600",
    textShadowColor: '#8EA7E9', 
    textShadowOffset: { width: 1, height: 1 },
    fontFamily: 'CuteFont_400Regular',
  },
  BreakerButton: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  BreakerButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  TTTSButton: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
 TTTSButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  SudokuButton: {
    backgroundColor: "transparent",  
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  SudokuButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 6,
  },
  MinesweeperButton: {
    backgroundColor: "transparent",  
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  MinesweeperButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  FlappyBirdButton: {
    backgroundColor: "transparent",  
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  FlappyBirdButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  Connect4SingleButton: {
    backgroundColor: "transparent",  
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Connect4SingleButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  TTTMButton: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TTTMButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  Connect4MultiButton: {
    backgroundColor: "transparent", 
    padding: 12,
    borderRadius: 10,
    margin: buttonMargin,
    width: buttonWidth,
    maxWidth: 140,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Connect4MultiButtonText: {
    color: "white",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    textShadowColor: 'black', 
    textShadowOffset: { width: 2, height: 1 }, 
    textShadowRadius: 1,
  },
  
  // Modalit
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: 'lightblue',
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: "white",
  },
  ModalButton: {
    backgroundColor: "rgb(58, 226, 255)",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  ModalButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: 'center'
  },
  difficultyModalContent: {
    backgroundColor: 'lightblue',
    padding: 20,
    borderRadius: 12,
    alignItems: "stretch",
    width: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: "space-between",
  },
  difficultyModalButton: {
    backgroundColor: "rgb(58, 226, 255)",
    paddingVertical: 10,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
  },
  difficultyModalButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
});
