import { Dimensions, StyleSheet } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const sectionPadding = 10;
const sectionWidth = windowWidth * 0.9;
const buttonSpacing = 10;
const buttonWidth = (sectionWidth - buttonSpacing) / 2;

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "rgb(157, 226, 255)",
    marginTop: 60,
  },
  logoImage: {
    width: '100%',
    height: 500,
    marginTop: -120,
  },
  input: {
    width: "70%",
    height: 42,
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 10,
    backgroundColor: "rgb(204, 159, 254)",
    color: "rgb(127, 0, 255)",
    marginTop: -100,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: "90%",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginHorizontal: 5,
    elevation: 3,
    marginRight: 20,
    marginLeft: 20,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  gameSection: {
    width: "96%",
    backgroundColor: "rgb(252, 130, 239)",
    borderRadius: 18,
    padding: sectionPadding,
    marginBottom: 20,
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 10,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 20,
    marginTop: 10,
    textAlign: "center",
  },
  fullScreen: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  scrollContainer: {
    flex: 1,
  },
  gameButtonsContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  backgroundImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  gameButton: {
    width: buttonWidth,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: buttonSpacing,
  },

  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: "rgb(204, 159, 254)",
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 10,
  },
  modalText: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: "rgb(127, 0, 255)",
  },
  ModalButton: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  ModalButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: 'center'
  },
  difficultyModalContent: {
    backgroundColor: "rgb(204, 159, 254)",
    padding: 20,
    borderRadius: 12,
    alignItems: "stretch",
    width: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: "space-between",
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 10,
  },
  difficultyModalButton: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingVertical: 10,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
  },
  difficultyModalButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
});