import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get("window");
const buttonsPerRow = 3;
const containerWidth = width * 0.80;
const spacing = width * 0.05;
const totalSpacing = spacing * (buttonsPerRow - 1);
const buttonWidth = (containerWidth - totalSpacing) / buttonsPerRow;

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "rgb(157, 226, 255)",
    marginTop: height * 0.07,
  },
  logoImage: {
    width: width,
    height: height * 0.29,
    marginTop: -5,
  },
  input: {
    width: width * 0.7,
    height: height * 0.045,
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 2,
    borderRadius: 8,
    paddingHorizontal: width * 0.03,
    marginBottom: height * 0.015,
    backgroundColor: "rgb(204, 159, 254)",
    color: "rgb(127, 0, 255)",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: width * 0.9,
    marginBottom: height * 0.02,
  },
  button: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingVertical: height * 0.012,
    paddingHorizontal: width * 0.045,
    borderRadius: 8,
    marginHorizontal: width * 0.04,
    elevation: 3,
  },
  buttonText: {
    color: "white",
    fontSize: width * 0.035,
    fontWeight: "bold",
    textAlign: "center",
  },
  gameSection: {
    width: width * 0.96,
    backgroundColor: "rgb(252, 130, 240)",
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 2,
    borderRadius: 18,
    marginBottom: height * 0.025,
    borderRadius: 10,
  },
  sectionTitle: {
    fontSize: width * 0.05,
    fontWeight: "bold",
    color: "#333",
    marginBottom: height * 0.02,
    marginTop: height * 0.012,
    textAlign: "center",
  },
  fullScreen: {
    flex: 1,
    width: width,
    height: height,
  },
  scrollContainer: {
    flex: 1,
  },
  gameButtonsContainer: {
    width: containerWidth,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  backgroundImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: width,
    height: height,
  },
  gameButton: {
    width: buttonWidth,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 2,
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: height * 0.02,
  },

  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: "rgb(204, 159, 254)",
    padding: width * 0.05,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderColor: "rgb(128, 0, 255)",
    borderWidth: 2,
    borderRadius: 10,
  },
  modalText: {
    fontSize: width * 0.045,
    fontWeight: "bold",
    marginBottom: height * 0.02,
    textAlign: "center",
    color: "rgb(127, 0, 255)",
  },
  ModalButton: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingHorizontal: width * 0.03,
    paddingVertical: height * 0.01,
    borderRadius: 8,
  },
  ModalButtonText: {
    color: "white",
    fontSize: width * 0.04,
    fontWeight: "bold",
    textAlign: 'center'
  },
  difficultyModalContent: {
    backgroundColor: "rgb(204, 159, 254)",
    padding: width * 0.05,
    borderRadius: 12,
    alignItems: "stretch",
    width: width * 0.8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: "space-between",
    borderColor: "rgb(127, 0, 255)",
    borderWidth: 5,
    borderRadius: 10,
  },
  difficultyModalButton: {
    backgroundColor: "rgb(127, 0, 255)",
    paddingVertical: height * 0.01,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: height * 0.007,
  },
  difficultyModalButtonText: {
    color: "white",
    fontSize: width * 0.04,
    fontWeight: "bold",
  },
});
